apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-processor
  namespace: staging
  labels:
    app: resume-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-processor
  template:
    metadata:
      labels:
        app: resume-processor
    spec:
      serviceAccountName: sqs-worker-sa
      containers:
      - name: resume-processor
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devresume-backend:${IMAGE_TAG}
        command: ["node", "dist/workers/resumeProcessor.js"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "staging"
        - name: AWS_REGION
          value: "${AWS_REGION}"
        - name: SQS_RESUME_UPDATES_URL
          valueFrom:
            secretKeyRef:
              name: sqs-urls
              key: resume-updates-url
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
  namespace: staging
  labels:
    app: pdf-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-generator
  template:
    metadata:
      labels:
        app: pdf-generator
    spec:
      serviceAccountName: sqs-worker-sa
      containers:
      - name: pdf-generator
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devresume-backend:${IMAGE_TAG}
        command: ["node", "dist/workers/pdfGenerator.js"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "staging"
        - name: AWS_REGION
          value: "${AWS_REGION}"
        - name: SQS_PDF_GENERATION_URL
          valueFrom:
            secretKeyRef:
              name: sqs-urls
              key: pdf-generation-url
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resume-processor-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resume-processor
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-generator-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-generator
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 